"""Initial schema

Revision ID: 40b9e910d3d8
Revises: 
Create Date: 2025-12-24 22:31:53.962049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40b9e910d3d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('discord_id', sa.String(length=50), nullable=True),
    sa.Column('discord_username', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('leagues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_invite_code'), 'leagues', ['invite_code'], unique=True)
    op.create_table('league_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PRE_DRAFT', 'DRAFTING', 'ACTIVE', 'COMPLETED', name='seasonstatus'), nullable=False),
    sa.Column('keep_teams', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=True),
    sa.Column('session_token', sa.String(length=100), nullable=True),
    sa.Column('rejoin_code', sa.String(length=20), nullable=True),
    sa.Column('format', sa.Enum('SNAKE', 'LINEAR', 'AUCTION', name='draftformat'), nullable=False),
    sa.Column('timer_seconds', sa.Integer(), nullable=True),
    sa.Column('budget_enabled', sa.Boolean(), nullable=False),
    sa.Column('budget_per_team', sa.Integer(), nullable=True),
    sa.Column('roster_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'LIVE', 'PAUSED', 'COMPLETED', name='draftstatus'), nullable=False),
    sa.Column('current_pick', sa.Integer(), nullable=False),
    sa.Column('pokemon_pool', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pick_order', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rejoin_code'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=True),
    sa.Column('draft_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_token', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('draft_position', sa.Integer(), nullable=True),
    sa.Column('budget_remaining', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('ties', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_picks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=True),
    sa.Column('picked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.UUID(), nullable=False),
    sa.Column('team_b_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('is_tie', sa.Boolean(), nullable=False),
    sa.Column('replay_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_pokemon',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=True),
    sa.Column('acquisition_type', sa.Enum('DRAFTED', 'TRADED', 'FREE_AGENT', name='acquisitiontype'), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('proposer_team_id', sa.UUID(), nullable=False),
    sa.Column('recipient_team_id', sa.UUID(), nullable=False),
    sa.Column('proposer_pokemon', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('recipient_pokemon', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='tradestatus'), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('admin_approved', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposer_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['recipient_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('team_pokemon')
    op.drop_table('matches')
    op.drop_table('draft_picks')
    op.drop_table('teams')
    op.drop_table('drafts')
    op.drop_table('seasons')
    op.drop_table('league_memberships')
    op.drop_index(op.f('ix_leagues_invite_code'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
